import {useState,useEffect,useCallback} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import {useAuth} from '../context/auth';
import api from '../Services/api';
export default function CmePacotes(){
 const location=useLocation(),navigate=useNavigate(),{usuario}=useAuth(),area=location.pathname.split('/')[2];
 const id=new URLSearchParams(location.search).get('pacote');
 const [lista,setLista]=useState([]),[pacote,setPacote]=useState(null),[materiais,setMateriais]=useState([]),[ciclos,setCiclos]=useState([]),[erro,setErro]=useState(''),[novo,setNovo]=useState(false),[salvando,setSalvando]=useState(false);
 const [nome,setNome]=useState(''),[itens,setItens]=useState([]),[cicloId,setCicloId]=useState(''),[validade,setValidade]=useState(''),[autoclave,setAutoclave]=useState(''),[resultado,setResultado]=useState('');
 const carregar=useCallback(async()=>{try{if(id){const [p,c]=await Promise.all([api.get(`/rastreabilidade/pacotes/${id}`),api.get('/esterilizacoes')]);setPacote(p.data);setCiclos(c.data);}else{const [p,m]=await Promise.all([api.get('/rastreabilidade/pacotes'),api.get('/materiais')]);setLista(p.data);setMateriais(m.data.filter(m=>m.tipo_material==='instrumental'&&m.passa_cme));}setErro('');}catch{setErro('Não foi possível carregar os pacotes do banco.');}},[id]);
 useEffect(()=>{setPacote(null);carregar();},[carregar]);
 const acao=async fn=>{if(salvando)return;setSalvando(true);setErro('');try{await fn();await carregar();}catch(e){setErro(e.response?.data?.message||'Não foi possível salvar.');}finally{setSalvando(false);}};
 const criar=e=>{e.preventDefault();acao(async()=>{const r=await api.post('/rastreabilidade/pacotes',{nome,itens});setNovo(false);navigate(`/app/${area}/cme/pacotes?pacote=${r.data.id}`);});};
 return <div className="flex-1 min-h-0 overflow-y-auto bg-white p-5 space-y-4"><button onClick={()=>id?navigate(`/app/${area}/cme/pacotes`):navigate(`/app/${area}/estoque`)}>← Voltar</button><h1 className="text-xl font-bold text-[#3B44A8]">CME — {id?'Pacote':'Pacotes'}</h1>{erro&&<p role="alert" className="text-red-600">{erro}</p>}
 {!id&&<><div className="grid grid-cols-3 gap-2 text-center text-xs">{[['aguardando','Aguardando'],['em_esterilizacao','Em esterilização'],['esterilizado','Liberados']].map(([s,t])=><div key={s} className="border rounded-xl p-2"><span className="block min-h-8">{t}</span><strong>{lista.filter(p=>p.status===s).length}</strong></div>)}</div><button onClick={()=>setNovo(!novo)} className="bg-[#F9A814] text-white rounded-xl p-3">+ Novo pacote</button>{novo&&<form onSubmit={criar} className="space-y-3 border rounded-xl p-3"><label className="block text-sm">Nome / tipo do pacote *<input required value={nome} onChange={e=>setNome(e.target.value)} className="block border p-2 w-full rounded-lg"/></label><p className="text-sm">Responsável pelo preparo: <strong>{usuario?.nome}</strong></p><h2 className="font-bold text-sm">Itens do pacote</h2>{materiais.map(m=>{const item=itens.find(i=>i.material_id===m.id);return <div key={m.id} className="flex gap-2 items-center text-sm"><label className="flex-1"><input type="checkbox" checked={!!item} onChange={e=>setItens(e.target.checked?[...itens,{material_id:m.id,quantidade:1}]:itens.filter(i=>i.material_id!==m.id))}/> {m.nome}</label>{item&&<input aria-label={`Quantidade de ${m.nome}`} required type="number" min="1" step="1" value={item.quantidade} onChange={e=>setItens(itens.map(i=>i.material_id===m.id?{...i,quantidade:Number(e.target.value)}:i))} className="border p-2 w-16 rounded-lg"/>}</div>;})}{!materiais.length&&<p className="text-sm">Cadastre instrumentais reutilizáveis que passam pelo CME para montar um pacote.</p>}<button disabled={salvando||!itens.length} className="bg-[#3B44A8] text-white p-3 rounded-xl disabled:opacity-50">Criar pacote</button></form>}{lista.map(p=><button key={p.id} onClick={()=>navigate(`/app/${area}/cme/pacotes?pacote=${p.id}`)} className="block text-left border rounded-xl p-3 w-full"><strong>CME{String(p.id).padStart(6,'0')} — {p.nome_pacote}</strong><p className="text-xs">{p.status.replaceAll('_',' ')}</p></button>)}</>}
 {id&&pacote&&<><h2 className="font-bold">{pacote.codigo} — {pacote.nome_pacote}</h2><p>Status: {pacote.status.replaceAll('_',' ')}</p><section className="border rounded-xl p-3 space-y-2"><h3 className="font-bold">Conteúdo do pacote</h3>{pacote.itens.map(i=><p key={i.material_id}>{i.quantidade} × {i.nome}</p>)}</section><p className="text-sm">Preparado por: {pacote.responsavel_preparo||'Não informado'}</p><p className="text-sm">Responsável pela esterilização: {pacote.responsavel_esterilizacao||'A definir no ciclo'}</p>{pacote.esterilizacao_id&&<p className="text-sm">Ciclo #{pacote.esterilizacao_id} — {pacote.equipamento} — {pacote.ciclo_status}</p>}
 {pacote.status==='aguardando'&&<section className="space-y-3 border rounded-xl p-3"><h3 className="font-bold">Esterilização</h3><label className="block text-sm">Ciclo<select value={cicloId} onChange={e=>setCicloId(e.target.value)} className="block border p-2 rounded-lg w-full"><option value="">Selecione</option>{ciclos.filter(c=>['pendente','em_andamento'].includes(c.status)).map(c=><option key={c.id} value={c.id}>#{c.id} — {c.equipamento} — {c.operador_nome}</option>)}</select></label><button disabled={salvando||!cicloId} onClick={()=>acao(()=>api.post(`/rastreabilidade/pacotes/${id}/processar`,{acao:'iniciar',ciclo_id:Number(cicloId)}))} className="bg-[#3B44A8] p-3 rounded-xl text-white disabled:opacity-50">Iniciar esterilização</button><details><summary className="text-sm">Cadastrar novo ciclo</summary><label className="block text-sm">Autoclave<input value={autoclave} onChange={e=>setAutoclave(e.target.value)} className="block border p-2 rounded-lg w-full"/></label><p className="text-xs">Responsável: {usuario?.nome}</p><button disabled={salvando||!autoclave.trim()} onClick={()=>acao(async()=>{const r=await api.post('/esterilizacoes',{equipamento:autoclave.trim(),tipo_ciclo:'vapor',status:'em_andamento'});setCicloId(String(r.data.id));})} className="text-sm underline">Criar ciclo</button></details></section>}
 {pacote.status==='em_esterilizacao'&&<section className="border rounded-xl p-3 space-y-3"><h3 className="font-bold">Resultado do ciclo</h3><label className="block text-sm">Resultado registrado<select value={resultado} onChange={e=>setResultado(e.target.value)} className="border rounded-lg p-2 block w-full"><option value="">Selecione</option><option value="aprovado">Aprovado</option><option value="reprovado">Reprovado</option></select></label><button disabled={salvando||!resultado||pacote.ciclo_status==='concluido'} onClick={()=>acao(()=>api.put('/esterilizacoes/'+pacote.esterilizacao_id,{status:'concluido',resultado}))} className="border rounded-xl p-3 disabled:opacity-50">Registrar conclusão do ciclo</button>{['professor','coordenador'].includes(usuario?.perfil)&&<button onClick={()=>navigate('/app/'+area+'/cme/controle-biologico')} className="block underline text-sm">Consultar controles do ciclo</button>}</section>}
 {pacote.status==='em_esterilizacao'&&['professor','coordenador'].includes(usuario?.perfil)&&<section className="space-y-3"><p className="text-sm">Conclua e aprove o ciclo e seus controles na área de esterilização antes da liberação.</p><label className="block">Validade<input type="date" value={validade} onChange={e=>setValidade(e.target.value)} className="block border p-2 rounded-lg"/></label><button disabled={salvando||!validade} onClick={()=>acao(()=>api.post(`/rastreabilidade/pacotes/${id}/processar`,{acao:'liberar',validade}))} className="bg-[#3B44A8] text-white p-3 rounded-xl">Liberar pacote</button></section>}
 {['esterilizado','utilizado','vencido'].includes(pacote.status)&&<button onClick={()=>navigate(`/app/${area}/estoque/configurar-etiqueta?pacote=${id}`)} className="bg-[#F9A814] text-white p-3 rounded-xl">Configurar etiqueta</button>}
 {pacote.status==='esterilizado'&&<button disabled={salvando} onClick={()=>acao(()=>api.post(`/rastreabilidade/pacotes/${id}/processar`,{acao:'utilizar'}))} className="block border rounded-xl p-3">Registrar utilização</button>}
 {['utilizado','vencido'].includes(pacote.status)&&<button onClick={()=>{setNome(pacote.nome_pacote);setItens(pacote.itens.map(i=>({material_id:i.material_id,quantidade:i.quantidade})));setNovo(true);navigate('/app/'+area+'/cme/pacotes');}} className="block border rounded-xl p-3">Preparar novo pacote com estes instrumentos</button>}
 <section className="space-y-2"><h3 className="font-bold">Histórico do pacote</h3>{pacote.historico.map(h=><p key={h.id} className="text-xs">{new Date(h.criado_em).toLocaleString('pt-BR')} · {h.evento} · {h.responsavel}</p>)}</section>
 </>}
 </div>;
}
