import {useState,useEffect} from 'react';
import {useLocation,useNavigate} from 'react-router-dom';
import api from '../Services/api';
export default function EntradaEstoque(){
 const location=useLocation(),navigate=useNavigate(),id=location.state?.material?.id;const area=location.pathname.split('/')[2];
 const [material,setMaterial]=useState(null),[lotes,setLotes]=useState([]),[erro,setErro]=useState(''),[salvando,setSalvando]=useState(false);
 const [d,setD]=useState({tipo:location.state?.tipo||'entrada',quantidade:'',lote:'',validade:'',data_recebimento:new Date().toLocaleDateString('sv-SE'),fornecedor:'',observacao:'',lote_id:''});
 useEffect(()=>{if(!id){setErro('Selecione um material no estoque.');return;}Promise.all([api.get(`/materiais/${id}`),api.get(`/rastreabilidade/materiais/${id}/lotes`)]).then(([m,l])=>{setMaterial(m.data);setLotes(l.data);}).catch(()=>setErro('Não foi possível carregar o material.'));},[id]);
 const salvar=async e=>{e.preventDefault();if(salvando)return;setSalvando(true);setErro('');try{await api.post(`/rastreabilidade/materiais/${id}/movimentos`,{...d,quantidade:Number(d.quantidade),lote_id:Number(d.lote_id)});navigate(`/app/${area}/estoque/detalhes`,{replace:true,state:{material}});}catch(e){setErro(e.response?.data?.message||'Não foi possível registrar a movimentação.');}finally{setSalvando(false);}};
 return <div className="flex-1 min-h-0 overflow-y-auto bg-white p-5 space-y-4"><button onClick={()=>navigate(-1)}>← Voltar</button><h1 className="font-bold text-xl text-[#3B44A8]">{d.tipo==='entrada'?'Entrada de estoque':'Saída de estoque'}</h1>{erro&&<p role="alert" className="text-red-600">{erro}</p>}{material&&<><h2 className="font-bold">{material.nome}</h2><p>{material.fabricante}</p><form onSubmit={salvar} className="space-y-4"><label className="block text-sm">Quantidade *<input type="number" min="1" step="1" required value={d.quantidade} onChange={e=>setD({...d,quantidade:e.target.value})} className="block border rounded-xl p-3 w-full"/></label>{d.tipo==='entrada'?<>{[['lote','Lote','text'],['validade','Validade','date'],['data_recebimento','Data de recebimento','date'],['fornecedor','Fornecedor','text']].map(([c,t,tipo])=><label key={c} className="block text-sm">{t}{c!=='fornecedor'?' *':''}<input type={tipo} required={c!=='fornecedor'} value={d[c]} onChange={e=>setD({...d,[c]:e.target.value})} className="block border rounded-xl p-3 w-full"/></label>)}</>:<label className="block text-sm">Lote *<select required value={d.lote_id} onChange={e=>setD({...d,lote_id:e.target.value})} className="block border rounded-xl p-3 w-full"><option value="">Selecione</option>{lotes.filter(l=>l.quantidade>0).map(l=><option key={l.id} value={l.id}>{l.lote} — {l.quantidade} disponíveis</option>)}</select></label>}<label className="block text-sm">Observação<textarea value={d.observacao} onChange={e=>setD({...d,observacao:e.target.value})} className="block border rounded-xl p-3 w-full"/></label><button disabled={salvando} className="bg-[#F9A814] text-white p-3 rounded-xl w-full">{salvando?'Salvando...':d.tipo==='entrada'?'Confirmar entrada':'Confirmar saída'}</button></form></>}</div>;
}
