import {useState,useEffect} from 'react';
import {createPortal} from 'react-dom';
import {useLocation,useNavigate} from 'react-router-dom';
import api from '../Services/api';
import './etiquetas.css';
export default function EtiquetaPacote(){
 const location=useLocation(),navigate=useNavigate(),area=location.pathname.split('/')[2];
 const [id,setId]=useState(new URLSearchParams(location.search).get('pacote')||''),[pacotes,setPacotes]=useState([]),[pacote,setPacote]=useState(null),[erro,setErro]=useState(''),[quantidade,setQuantidade]=useState(1);
 useEffect(()=>{api.get('/rastreabilidade/pacotes').then(r=>setPacotes(r.data)).catch(()=>setErro('Não foi possível carregar os pacotes.'));},[]);
 useEffect(()=>{let ativo=true;setPacote(null);if(id)api.get(`/rastreabilidade/pacotes/${id}/etiqueta`).then(r=>{if(ativo){setPacote(r.data);setErro('');}}).catch(e=>{if(ativo)setErro(e.response?.data?.message||'Não foi possível gerar a etiqueta.');});return()=>{ativo=false;};},[id]);
 const etiqueta=pacote&&<article className="etiqueta etiqueta-pacote"><strong>CLÍNICA ODONTO — {pacote.nome_pacote}</strong><div className="etiqueta-pacote-corpo"><div><p>Pacote: {pacote.codigo}</p><p>Ciclo: {pacote.esterilizacao_id}</p><p>Esterilização: {pacote.esterilizado_em?.slice(0,10).split('-').reverse().join('/')||'Não informada'}</p><p>Validade: {pacote.validade?.slice(0,10).split('-').reverse().join('/')||'Não informada'}</p><p>Responsável: {pacote.responsavel_esterilizacao||'Não informado'}</p></div><div><img src={pacote.qr_code} alt={`QR Code do pacote ${pacote.codigo}`} className="etiqueta-pacote-qr"/><div>{pacote.codigo}</div></div></div></article>;
 return <div className="flex-1 min-h-0 overflow-y-auto bg-white p-5 space-y-4"><button onClick={()=>navigate(`/app/${area}/cme/pacotes`)}>← Pacotes CME</button><h1 className="font-bold text-xl text-[#3B44A8]">Configurar etiqueta do pacote</h1><label className="block text-sm">Pacote<select value={id} onChange={e=>setId(e.target.value)} className="block border p-3 rounded-xl w-full"><option value="">Selecione um pacote liberado</option>{pacotes.filter(p=>['esterilizado','utilizado','vencido'].includes(p.status)).map(p=><option key={p.id} value={p.id}>CME{String(p.id).padStart(6,'0')} — {p.nome_pacote}</option>)}</select></label>{erro&&<p role="alert" className="text-red-600">{erro}</p>}{pacote&&<><label className="block text-sm">Responsável pela esterilização<input readOnly value={pacote.responsavel_esterilizacao||'Não informado'} className="block border rounded-xl p-3 w-full bg-gray-50"/></label><p className="text-xs">Nome registrado no ciclo. O QR identifica este pacote e permite consultar seu conteúdo no sistema.</p><section className="border rounded-xl p-3 text-sm"><h2 className="font-bold">Materiais no pacote</h2>{pacote.itens.map(i=><p key={i.material_id}>{i.quantidade} × {i.nome}</p>)}</section><div className="bg-gray-100 p-2 overflow-auto">{etiqueta}</div><label className="block text-sm">Quantidade de etiquetas<input type="number" min="1" max="100" value={quantidade} onChange={e=>setQuantidade(Math.min(100,Math.max(1,Number(e.target.value)||1)))} className="block border p-3 rounded-xl"/></label><button onClick={()=>window.print()} className="bg-[#3B44A8] text-white p-3 rounded-xl w-full">Imprimir etiquetas</button><p className="text-xs">Papel 70 × 50 mm, escala 100%. Confira a impressão e faça uma leitura de teste.</p>{createPortal(<div className="etiquetas-impressao">{Array.from({length:quantidade},(_,i)=><div key={i}>{etiqueta}</div>)}</div>,document.body)}</>}</div>;
}
